/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedIdentityRouteImport } from './routes/_authenticated/identity'
import { Route as AuthenticatedGisRouteImport } from './routes/_authenticated/gis'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdentityRoute = AuthenticatedIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGisRoute = AuthenticatedGisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gis': typeof AuthenticatedGisRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/media': typeof AuthenticatedMediaRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/search': typeof AuthenticatedSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gis': typeof AuthenticatedGisRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/media': typeof AuthenticatedMediaRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/search': typeof AuthenticatedSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gis': typeof AuthenticatedGisRoute
  '/_authenticated/identity': typeof AuthenticatedIdentityRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/audit'
    | '/campaigns'
    | '/dashboard'
    | '/gis'
    | '/identity'
    | '/knowledge'
    | '/media'
    | '/notifications'
    | '/organizations'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/audit'
    | '/campaigns'
    | '/dashboard'
    | '/gis'
    | '/identity'
    | '/knowledge'
    | '/media'
    | '/notifications'
    | '/organizations'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/analytics'
    | '/_authenticated/audit'
    | '/_authenticated/campaigns'
    | '/_authenticated/dashboard'
    | '/_authenticated/gis'
    | '/_authenticated/identity'
    | '/_authenticated/knowledge'
    | '/_authenticated/media'
    | '/_authenticated/notifications'
    | '/_authenticated/organizations'
    | '/_authenticated/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identity': {
      id: '/_authenticated/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof AuthenticatedIdentityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gis': {
      id: '/_authenticated/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof AuthenticatedGisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGisRoute: typeof AuthenticatedGisRoute
  AuthenticatedIdentityRoute: typeof AuthenticatedIdentityRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGisRoute: AuthenticatedGisRoute,
  AuthenticatedIdentityRoute: AuthenticatedIdentityRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
